# Generated by Django 4.0.5 on 2022-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_reviewer_analysisofalgorithms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='Topic',
            field=models.CharField(choices=[('a', 'AnalysisOfAlgorithms'), ('a', 'Application'), ('a', 'Architecture'), ('a', 'ArtificialIntelligence'), ('c', 'ComputerEngineering'), ('c', 'Curriculum'), ('d', 'DataStructures'), ('d', 'Databases'), ('d', 'DistanceLearning'), ('d', 'DistributedSystems'), ('e', 'EthicalSocietalIssues'), ('f', 'FirstYearComputing'), ('g', 'GenderIssues'), ('g', 'GrantWriting'), ('g', 'GraphicsImageProcessing'), ('h', 'HumanComputerInteraction'), ('l', 'LaboratoryEnvironments'), ('l', 'Literacy'), ('m', 'MathematicsInComputing'), ('m', 'Multimedia'), ('n', 'NetworkingDataCommunications'), ('n', 'NonMajorCourses'), ('o', 'ObjectOrientedIssues'), ('o', 'OperatingSystems'), ('p', 'ParallelProcessing'), ('p', 'Pedagogy'), ('p', 'ProgrammingLanguages'), ('r', 'Research'), ('s', 'Security'), ('s', 'SoftwareEngineering'), ('s', 'SystemsAnalysisAndDesign'), ('u', 'UsingTechnologyInTheClassroom'), ('w', 'WebAndInternetProgramming'), ('o', 'Other')], default=None, max_length=50),
        ),
    ]
