# Generated by Django 4.0.5 on 2022-07-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_reviewer_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='Active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='OtherDescription',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='ReviewsAcknowledged',
            field=models.BooleanField(null=True),
        ),
    ]
