# Generated by Django 4.0.5 on 2022-07-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_reviewer_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='Active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='OtherDescription',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='ReviewsAcknowledged',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
