# Generated by Django 4.0.5 on 2022-07-08 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_paper_analysisofalgorithms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='AuthorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.author', unique=True),
        ),
    ]
