# Generated by Django 4.0.5 on 2022-07-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_paper_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='AuthorID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.author', unique=True),
        ),
    ]
