# Generated by Django 4.0.5 on 2022-07-09 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_paper_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='user',
            new_name='user_ref',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='AuthorID',
        ),
        migrations.AddField(
            model_name='paper',
            name='BeingReviewed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='author_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Topic',
            field=models.CharField(choices=[('AnalysisOfAlgorithms', 'AnalysisOfAlgorithms'), ('Application', 'Application'), ('Architecture', 'Architecture'), ('ArtificialIntelligence', 'ArtificialIntelligence'), ('ComputerEngineering', 'ComputerEngineering'), ('Curriculum', 'Curriculum'), ('DataStructures', 'DataStructures'), ('Databases', 'Databases'), ('DistanceLearning', 'DistanceLearning'), ('DistributedSystems', 'DistributedSystems'), ('EthicalSocietalIssues', 'EthicalSocietalIssues'), ('FirstYearComputing', 'FirstYearComputing'), ('GenderIssues', 'GenderIssues'), ('GrantWriting', 'GrantWriting'), ('GraphicsImageProcessing', 'GraphicsImageProcessing'), ('HumanComputerInteraction', 'HumanComputerInteraction'), ('LaboratoryEnvironments', 'LaboratoryEnvironments'), ('Literacy', 'Literacy'), ('MathematicsInComputing', 'MathematicsInComputing'), ('Multimedia', 'Multimedia'), ('NetworkingDataCommunications', 'NetworkingDataCommunications'), ('NonMajorCourses', 'NonMajorCourses'), ('ObjectOrientedIssues', 'ObjectOrientedIssues'), ('OperatingSystems', 'OperatingSystems'), ('ParallelProcessing', 'ParallelProcessing'), ('Pedagogy', 'Pedagogy'), ('ProgrammingLanguages', 'ProgrammingLanguages'), ('Research', 'Research'), ('Security', 'Security'), ('SoftwareEngineering', 'SoftwareEngineering'), ('SystemsAnalysisAndDesign', 'SystemsAnalysisAndDesign'), ('UsingTechnologyInTheClassroom', 'UsingTechnologyInTheClassroom'), ('WebAndInternetProgramming', 'WebAndInternetProgramming'), ('Other', 'Other')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='Topic',
            field=models.CharField(choices=[('AnalysisOfAlgorithms', 'AnalysisOfAlgorithms'), ('Application', 'Application'), ('Architecture', 'Architecture'), ('ArtificialIntelligence', 'ArtificialIntelligence'), ('ComputerEngineering', 'ComputerEngineering'), ('Curriculum', 'Curriculum'), ('DataStructures', 'DataStructures'), ('Databases', 'Databases'), ('DistanceLearning', 'DistanceLearning'), ('DistributedSystems', 'DistributedSystems'), ('EthicalSocietalIssues', 'EthicalSocietalIssues'), ('FirstYearComputing', 'FirstYearComputing'), ('GenderIssues', 'GenderIssues'), ('GrantWriting', 'GrantWriting'), ('GraphicsImageProcessing', 'GraphicsImageProcessing'), ('HumanComputerInteraction', 'HumanComputerInteraction'), ('LaboratoryEnvironments', 'LaboratoryEnvironments'), ('Literacy', 'Literacy'), ('MathematicsInComputing', 'MathematicsInComputing'), ('Multimedia', 'Multimedia'), ('NetworkingDataCommunications', 'NetworkingDataCommunications'), ('NonMajorCourses', 'NonMajorCourses'), ('ObjectOrientedIssues', 'ObjectOrientedIssues'), ('OperatingSystems', 'OperatingSystems'), ('ParallelProcessing', 'ParallelProcessing'), ('Pedagogy', 'Pedagogy'), ('ProgrammingLanguages', 'ProgrammingLanguages'), ('Research', 'Research'), ('Security', 'Security'), ('SoftwareEngineering', 'SoftwareEngineering'), ('SystemsAnalysisAndDesign', 'SystemsAnalysisAndDesign'), ('UsingTechnologyInTheClassroom', 'UsingTechnologyInTheClassroom'), ('WebAndInternetProgramming', 'WebAndInternetProgramming'), ('Other', 'Other')], default=None, max_length=50),
        ),
    ]
