# Generated by Django 4.0.5 on 2022-07-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_origanizationofpaper_review_organizationofpaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ClarityOfMainMessage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='ContentComments',
            field=models.TextField(),
        ),
    ]
